package com.example.vvs.VVS.Project;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CadastroProfessorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cadastroProfessor() {
    driver.get("https://curso-sistema.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.cssSelector(".waves-effect:nth-child(3)")).click();
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("ProfessorSelenium");
    driver.findElement(By.name("cargaHoraria")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".waves-effect:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("cargaHoraria")).sendKeys("50");
    driver.findElement(By.cssSelector(".waves-effect:nth-child(2)")).click();
  }
}
