package com.example.vvs.VVS.Project;// Generated by Selenium IDE
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class CadastroProfessorTest {
     /*
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }


    @Test
    public void cadastroProfessor() {
        driver.get("https://curso-sistema.herokuapp.com/");
        driver.manage().window().setSize(new Dimension(1920, 1080));
        driver.findElement(By.cssSelector(".waves-effect:nth-child(3)")).click();
        driver.findElement(By.name("nome")).click();
        driver.findElement(By.name("nome")).sendKeys("ProfessorSelenium");
        driver.findElement(By.name("cargaHoraria")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".waves-effect:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.name("cargaHoraria")).sendKeys("50");
        driver.findElement(By.cssSelector(".waves-effect:nth-child(2)")).click();
    }*/
}